version: '3'

services:
  zookeeper:
    image: bitnami/zookeeper:3.4.12
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  metrics-paradise:
    image: metrics-paradise:1.0.0
    ports:
      - 8080:8080
    depends_on:
      - zookeeper
      - graphite
    environment:
      - _JAVA_OPTIONS=
       -Dzookeeper.host=zookeeper
       -Dlog.level=info
       -Ddb.h2.url=jdbc:h2:/usr/share/metrics-paradise/db
       -Dmonitoring.enabled=true

  graphite:
    image: hopsoft/graphite-statsd
    ports:
      - 2003
      - 8090:80

  jmeter:
    image: justb4/jmeter
    depends_on:
      - graphite
      - metrics-paradise
    volumes:
      - ./config/20k-10thread.jmx:/tests/3devices.jmx
    command: -n -t "/tests/3devices.jmx"

  grafana:
    image: grafana/grafana
    environment:
      - GF_LOG_LEVEL=warn
    ports:
     - 3000:3000
    depends_on:
      - graphite
    volumes:
      - ./config/graphite.yaml:/etc/grafana/provisioning/datasources/graphite.yaml
      - ./config/dbprovider.yaml:/etc/grafana/provisioning/dashboards/dbprovider.yaml
      - ./config/jmeter-dashboard.json:/var/lib/grafana/dashboards/jmeter-dashboard.json
      - ./config/metrics-paradise-dashboard.json:/var/lib/grafana/dashboards/metrics-paradise-dashboard.json



