version: '3'

services:
  zookeeper:
    image: bitnami/zookeeper:3.4.12
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  metrics-paradise:
    image: metrics-paradise:1.0.0
    ports:
      - 8080:8080
    depends_on:
      - zookeeper
      - graphite
    environment:
      - _JAVA_OPTIONS='-Dzookeeper.host=zookeeper'

  graphite:
    image: hopsoft/graphite-statsd
    ports:
      - 2003
      - 8090:80

  jmeter:
    image: justb4/jmeter
    depends_on:
      - graphite
      - metrics-paradise
    volumes:
      - ./config/3devices.jmx:/tests/3devices.jmx
    command: -n -t "/tests/3devices.jmx"



